title: JTPMATH
description: Welcome to jtpmath!
theme: just-the-docs

url: https://jtpmath.github.io

aux_links:
  Youtube: https://youtube.com/@jtpmath

logo: "/assets/watermark-01.jpg"

favicon_ico: "/assets/logo-official.jpg"

collections:
  blog:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: "blog"
    values:
      layout: "default"
      parent: "Blog"


