title: JTPMATH
description: Welcome to jtpmath!
theme: just-the-docs

url: https://jtpmath.github.io

aux_links:
  Youtube: https://youtube.com/@jtpmath

logo: "/assets/watermark-01.jpg"

favicon_ico: "/assets/logo-official.jpg"

collections:
  blog:
    output: true
    permalink: /blog/:path/

# Add a default configuration for Blog.md
defaults:
  - scope:
      path: "blog"
    values:
      layout: "default"
      parent: "Blog"
  - scope:
      path: ""
      type: blog
    values:
      layout: default
      nav_order: 6  # Adjust this order as needed
      
nav:
  - title: "Blog"
    url: "/blog/"
    nav_order: 6
      
plugins:
  - jekyll-paginate

paginate: 5  # Number of posts per page
paginate_path: "/blog/page:num"



